theme: jekyll-theme-hacker
title: Merlijn Vermeer
description: Cyber Security Minor
include: ['_pages']


defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      permalink: ""